server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rgusto/microservice-repo
          search-paths: microservice-spring-cloud-alura/fornecedor